#!/bin/bash
# Quick reference commands for SmartJobHunter Pro

echo "=========================================="
echo "🚀 SmartJobHunter Pro - Quick Commands"
echo "=========================================="
echo ""

echo "📦 SETUP (First Time Only)"
echo "----------------------------"
echo "1. Get API Key: https://makersuite.google.com/app/apikey"
echo "2. Copy .env.example to .env"
echo "   cp .env.example .env"
echo "3. Edit .env and add your GEMINI_API_KEY"
echo "   nano .env"
echo ""

echo "🔧 ACTIVATE PYTHON ENVIRONMENT"
echo "----------------------------"
echo "cd backend"
echo "source jobHunter/bin/activate"
echo ""

echo "🚀 START APPLICATION"
echo "----------------------------"
echo ""
echo "Option 1: Docker (Recommended)"
echo "  docker-compose up"
echo ""
echo "Option 2: Manual"
echo "  # Terminal 1 - Backend"
echo "  cd backend"
echo "  source jobHunter/bin/activate"
echo "  uvicorn app:app --reload"
echo ""
echo "  # Terminal 2 - Frontend"
echo "  cd frontend"
echo "  npm install"
echo "  npm run dev"
echo ""

echo "🌐 ACCESS"
echo "----------------------------"
echo "Frontend:  http://localhost:3000"
echo "API Docs:  http://localhost:8000/docs"
echo "API:       http://localhost:8000"
echo "Health:    http://localhost:8000/health"
echo ""

echo "🧪 TEST COMMANDS"
echo "----------------------------"
echo "# Test Python environment"
echo "cd backend && source jobHunter/bin/activate && python -c 'print(\"✅ Working!\")'"
echo ""
echo "# Test database connection"
echo "cd backend && source jobHunter/bin/activate && python -c 'from database import SessionLocal; db = SessionLocal(); print(\"✅ DB OK\"); db.close()'"
echo ""
echo "# Test API key (after adding to .env)"
echo "cd backend && source jobHunter/bin/activate && python -c 'from dotenv import load_dotenv; import os; load_dotenv(\"../.env\"); print(\"✅\" if os.getenv(\"GEMINI_API_KEY\") else \"❌\")'"
echo ""

echo "📝 USEFUL COMMANDS"
echo "----------------------------"
echo "# Initialize database"
echo "cd backend && source jobHunter/bin/activate && python -c 'from database import init_db; init_db()'"
echo ""
echo "# Seed companies"
echo "cd backend && source jobHunter/bin/activate && python scripts/seed_companies.py"
echo ""
echo "# Check installed packages"
echo "cd backend && source jobHunter/bin/activate && pip list"
echo ""
echo "# View logs"
echo "tail -f logs/jobhunter.log"
echo ""

echo "🛑 STOP APPLICATION"
echo "----------------------------"
echo "Docker: docker-compose down"
echo "Manual: Ctrl+C in each terminal"
echo ""

echo "=========================================="
